### ISSUE TITLE
Play my recording

### ISSUE THREAD

**Issue by saber-dev** [saebekassebil/microphone-stream#12]
Hi, 

It's not an issue. It's just a request :)

I would like to know. Can I play the raw ? if yes how ?

**Comment by nfriedly** [comment]
It is possible, but the raw audio stream is not in a very common format. You can send it right back without changing the format by using another scriptProcessorNode: https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode

If you want to convert it to a more common format, https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/webaudio-l16-stream.js can convert it to "raw wav" format and then https://www.npmjs.com/package/wav can add the header to make it a proper wav file. (Although wav is tricky because the header is supposed to know the length of the file, so you can't finish the header until you're done recording. The `wav` package has a method to do that for you, but it expects filesystem access, so that won't work in a browser unless you also have a fake `fs` module.)

Or you could skip this library and use the native MediaRecorder API if you don't need access to the raw audio and just want a playable output file: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API - the example on https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder includes playback support

**Comment by saber-dev** [comment]
Hi, 

Thank you, 
It is only to listen to it live what I write :)

**Comment by nfriedly** [comment]
Sounds good. I'm going to close this for now.
