### ISSUE TITLE
Best way to pause/resume stream

### ISSUE THREAD

**Issue by hansy** [saebekassebil/microphone-stream#14]
What's the best way to pause/resume a stream?

It it better to request the audio stream once (via `getUserMedia`) and then "sample" the stream during recording sessions, or to initialize a new audio stream every time?

Does my question make sense?

**Comment by nfriedly** [comment]
Hi @hansy, that makes sense.

Initializing a new stream every time isn't always a good choice because some browsers ask for permission again each time.

The underlying AudioContext has `.suspend()` and `.resume()` methods - The AudioContext is now exposed as `micStream.context`, so `micStream.context.suspend()` and `micStream.context.resume()`. That's probably the best option in modern browsers, but it isn't necessarily available in older browsers, and `resume()` can only be triggered in response to a user tap in most mobile browsers. 

In other places, such as [watson-speech](https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-microphone.js#L30), I have it un-piping the micStream, and instead piping it's audio to a no-op "bitbucket" WritableStream. (You don't want to leave it un-piped because it will then buffer all of it's audio and unleash it in a giant flood the next time you re-piped it.)

I've been thinking about this a bit lately and considering adding some sort of pause/resume mechanism to this library that would attempt to smooth over the various issues and just choose whichever method worked best. But I haven't gotten that far yet, so these two options are what's available for the moment.

**Comment by hansy** [comment]
I appreciate the prompt reply and suggestions. I'll explore the options you presented and see if I can make something work. Thank you so much for your help!

**Comment by ghost** [comment]
@nfriedly does this also go for .stop()? I am noticing that after calling .stop() I cannot simply restart the stream by calling a new GetUserMedia

**Comment by nfriedly** [comment]
Yea, .stop() shuts everything down, and then you have to create a new stream the next time you want audio.

**Comment by nfriedly** [comment]
#29 added a simple `.play()` and `.pause()` API, it's now published to npm in v5.1.0, so I'm going to go ahead and close this.

**Comment by kpatil001** [comment]
> #29 added a simple `.play()` and `.pause()` API, it's now published to npm in v5.1.0, so I'm going to go ahead and close this.

That's great, I was trying it out, micStream.pause() is working perfectly but micStream.play(); is giving me error "micStream.play is not a function" same goes for micStream.context.play(). Am I implementing it in wrong manner ?

**Comment by nfriedly** [comment]
Op, sorry, they were actually named `pauseRecording()` and `playRecording()`

**Comment by nfriedly** [comment]
(`pause()` is an [API of the underlying stream interface](https://nodejs.org/api/stream.html#stream_readable_pause) that causes data to be buffered, whereas the new `pauseRecording()` API drops new data)

**Comment by kpatil001** [comment]
> Op, sorry, they were actually named `pauseRecording()` and `playRecording()`

Thanks for the prompt reply. I tried to use micStream.pauseRecording(). But it throws exception  "TypeError: micStream.pauseRecording is not a function" .  I am using microphone-stream v5.1.0.  So can you please throw some light on correct way of using these functions.

**Comment by nfriedly** [comment]
Hum.. that's confusing. It looks like it's there in the release  - e.g. see https://unpkg.com/microphone-stream@5.1.0/microphone-stream.js

Do you mind posting your code?
