### ISSUE TITLE
Connect stream to google speech api

### ISSUE THREAD

**Issue by vin-ni** [saebekassebil/microphone-stream#15]
Hi,
I just started with node.js and am trying to connect the generated microphone stream from the browser with the google speech api running on my node server. 

I successfully packed everything with browserify, but now don't know how to proceed. I got the microphone stream to work on the node server as well (as explained here: [Streaming Speech Recognition on an Audio Stream](https://cloud.google.com/speech/docs/streaming-recognize) ).

How can I transmit the audiostream? I read about using websockets in one issue, but didn't really understand if it's the right way in my case. For now I'm using these packages on the server:

```
const express = require('express');
const path = require('path');
const bodyParser = require('body-parser');
const fs = require('fs');
const record = require('node-record-lpcm16');
const google = require('googleapis');
const getUserMedia = require('get-user-media-promise');
const MicrophoneStream = require('microphone-stream');
``` 

This is my first time using node / a server, so hopefully this question isn't too naive.
Thanks! :)

**Comment by nfriedly** [comment]
Hi @vin-ni,

I think you may be trying to do a bit bigger project than you realized. WebSockets would be a way to do this, although that's kind of a high-level answer.

The first route to consider could be bypassing your node.js server and just connecting directly from the browser to google. This is how the IBM [watson-speech](https://www.npmjs.com/package/watson-speech) library uses `microphone-stream` - you can see the websocket code at https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-stream.js

I didn't see any google code for that, although you could always try their node.js code in browserify/webpack and see if it works :)

Otherwise you'll need to do something similar to the watson code on the client, and then the reverse side of that on your server, and then send it on to google.  You could try out https://www.npmjs.com/package/websocket-stream or a similar package, but I've never used any of them, so I can't comment on how well it would work.

Or, as I'm of course obligated to mention, you could ditch google and try watson ;) We have a pretty friendly SDK and a boatload of examples at https://watson-speech.mybluemix.net/

**Comment by tdeoliveira05** [comment]
I am in the same situation as Vin-Ni

I am attempting to stream the resultant `micStream` from the client to my (nodeJS) ExpressJS server which would then stream to google's cloud speech API to obtain a transcript to send back to the client.

I love Watson's ease of use for this stuff but recently we found the quality of Google's api is better... It just happens to be a much bigger pain to set up...

Any ideas other than websockets here? 

I wish i could just beam it up to the server through axios...

**Comment by vin-ni** [comment]
@tdeoliveira05 
I built a small cross-device base with socket.io that might help you. Just add your google key and it should work :)
https://github.com/vin-ni/Google-Cloud-Speech-Node-Socket-Playground

**Comment by tdeoliveira05** [comment]
@vin-ni Awesome, thanks!

**Comment by vin-ni** [comment]
@tdeoliveira05 tell me if it worked, or if I can add any improvements to it

**Comment by nfriedly** [comment]
Yea, sorry, I had written up a response but it apparently never posted. I think @vin-ni's solution is probably better, but here's what I wrote previously FWIW:

---

WebSockets are prettymuch the only sane way to do it in near-realtime. 

If you don't need live transcription, you can buffer up the audio until it's done, and then POST that to your server (or possibly directly to google). It'll be simpler, although at that point, you probably don't need this library; the built-in [MediaRecorder](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder) API can buffer up audio.

Also, FWIW, the part that makes Watson good is the ability to train it. Google may be better out of the box, but you don't really have any recourse when it does get things wrong. With Watson, you can correct it and end up with a system that works better than Google's for your use-case. (I used to work for IBM Watson, so I'm probably a little biased, but still...)

**Comment by tdeoliveira05** [comment]
@nfriedly thanks!

@vin-ni I integrated your code into mine and it seems to work great! I did have a question which i posted on the issues for whenever you have time!
