### ISSUE TITLE
Possible to detect when no audio/talking is happening?

### ISSUE THREAD

**Issue by JoshKing87** [saebekassebil/microphone-stream#27]
Hello, I'm able to get this code running great! 

I was wondering if there was a way to detect when no user audio input is being detected? For example if a user is talking, and then stops talking data is being processed, but when they stop talking I want to STOP processing data. Is there a way to detect that absence of talking?

**Comment by nfriedly** [comment]
Hi @JoshKing87, 

This is possible, but can get complex. The "simple" version is to just keep a running average of the volume level and watch when it goes above or below some threshold. You probably want to have a delay before stopping so that it doesn't stop in between each word. 

A more complex version might first filter out anything outside the frequency range of human voice and then perform the above logic.

In either case, though, I think it would make more sense in a standalone module rather than as part of this one.
