### ISSUE TITLE
Fails to work with react-native-webrtc

### ISSUE THREAD

**Issue by soesujith** [saebekassebil/microphone-stream#37]
This fails to work when try using with react-native-webrtc mediastream in mobile devices. 
Gets the following error;

`react native TypeError: AudioContext is not a constructor at new MicrophoneStream (microphone-stream.js:61)`

Is there a way to make it workable or similar package that works in react-native

**Comment by nfriedly** [comment]
It looks like that's not going to be easy to fix, see https://github.com/react-native-webrtc/react-native-webrtc/issues/276#issuecomment-395623377

microphone-stream only needs the AudioContext in order to call createScriptProcessor - that's how we get the raw audio data into JavaScript. But I don't see any references to it in the react-native-webrtc code.

I'm not really up-to-speed on audio in React Native, but what is you end goal? My gut feeling is that sending the audio data through JavaScript isn't the best solution if you can avoid it. Depending on what you're trying to accomplish, there may be a native module that does it for you.

You might also ask the folks behind react-native-webrtc if they have any advice.

**Comment by nfriedly** [comment]
I'm going to close this ticket for now since I don't think there is a feasible solution that involves this project.

**Comment by kostiantyn-solianyk** [comment]
@sbsujith Hey! Did you find a solution to this issue, I'll be happy to hear something from you.
