### ISSUE TITLE
Browserify'd the example, window hangs

### ISSUE THREAD

**Issue by joshterrill** [saebekassebil/microphone-stream#7]
Hey there,

Wanting to do some experimenting with audio streams, came across a stack overflow post recommending your library. I tried to browserify your example code and output it to a bundle.js, when I load it in my web server, it just hangs and never completely loads. Has anyone else experienced this?

**Comment by nfriedly** [comment]
Hi @joshterrill,

I wrote most of the example in the README, and I admit, it's not really a working example:
- The `getUserMedia` fires immediately on load rather than waiting for the user to click a button or something. I think this is blocked in at least some browsers. 
- The `micStream.on('data', ...` callback doesn't actually do anything
- The `micStream.pipe(/*...*/)` doesn't have a target. You need to pass in a  WriteableStream for this to work at all.
- Normally you'd have either an `.on('data',...` or a `.pipe(...)` but not both.

I really meant it as more of an overview of the API: Copy-paste the bits you need and adapt to suit. I think it would normally log the format to the console, but the broken call to `.pipe()` might prevent that. 

Take a look at https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-microphone.js for a working example of this lib in use.
