### ISSUE TITLE
Get Blob from the stream

### ISSUE THREAD

**Issue by quanglam2807** [saebekassebil/microphone-stream#8]
I tried to use your library to record the audio, together with `watson-speech/speech-to-text/webaudio-l16-stream` but I don't know how to convert the stream to blob. I tried to play the blob with the code below but the blob is invalid. Also, I tried to send the blob to Google Speech API v2 but it returns that the blob as invalid.

``` javascript
import L16 from 'watson-speech/speech-to-text/webaudio-l16-stream';
import MicrophoneStream from 'microphone-stream';

let micStream;
let l16Stream;

export const stopRecording = () => ((dispatch, getState) => {
  const blob = new Blob([l16Stream.read()], { type: 'audio/l16' });

  const player = new Audio(URL.createObjectURL(blob, { oneTimeOnly: true }));
  player.play(); // Error: Failed to load because no supported source was found.
})

export const startRecording = () => ((dispatch) => {
  dispatch({
    type: UPDATE_SPEECH_STATUS,
    status: 'recording',
  });

  navigator.getUserMedia({ audio: true, video: false }, (stream) => {
    micStream = new MicrophoneStream(stream, {
      objectMode: false,
      bufferSize: null,
    });

    l16Stream = new L16({ writableObjectMode: false });
    micStream.pipe(l16Stream);
  }, () => {
    // error
  });
});
```

Can you help me with this? It would be great if you can also add an example for this case to `README`.

**Comment by nfriedly** [comment]
I think your issue is that `stream.read()` doesn't actually return any data - it just switches the stream from paused to flowing if it happens to be paused. flowing means that it emits `data` events with the actual data as it becomes available. See https://nodejs.org/api/stream.html#stream_readable_streams for more details.

My internet seems to be partially down this morning (presumably the same DNS problems that were affecting a lot of people last week), but I think this is a package that can help: https://www.npmjs.com/package/concat-stream

It collects all of the data and returns a single Buffer (which I think can then be converted to a Blob).

The other thing I should mention, is that if you just want to record and play back audio within the browser, you might want to drop this library and check out https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder_API - it might be a better fit for your needs.

**Comment by quanglam2807** [comment]
Thank you very much, @nfriedly! I am now using another solution as you suggested.
